scheduler-salesforce-app/force-app/main/default/objects/SchedulerEvent__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>EndTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SchedulerEvent__c/fields/RecurrenceRule__c.field-meta.xml
<CustomField>
    <fullName>RecurrenceRule__c</fullName>
    <label>RecurrenceRule</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

scheduler-salesforce-app/force-app/main/default/objects/SchedulerEvent__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>StartTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/SchedulerData.cls
public with sharing class SchedulerData {
    @RemoteAction
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getEvents() {
 
        // fetching the Events via salesforce backend
        List<SchedulerEvent__c> Events = new List<SchedulerEvent__c>();
        Events = [SELECT Id, Name, Start_Time__c, End_Time__c, IsAllDay__c,
            Location__c, RecurrenceRule__c FROM SchedulerEvent__c];
 
        Map<String, Object> result = new Map<String, Object>{'events' => Events };
        return result;
   }
}